"""Общие константы meeting agent / slot preview."""

DEFAULT_DURATION_MINUTES = 60
SLOT_PREVIEW_MAX_DAYS = 30
SLOT_PREVIEW_TIMEOUT_SECONDS = 180
QUORUM_MIN_COVERAGE_RATIO = 0.7
QUORUM_MAX_CANDIDATES = 3
QUORUM_VERIFY_TOP_N = 3
MEMO_FETCH_LIMIT = 50
MEMO_FETCH_POOL = 200
