from __future__ import annotations
TOOL_NAMES: list[str] = [
    "list_available_knowledge_bases",
    "search_knowledge_base",
    "get_knowledge_fragment",
    "get_document_metadata",
    "get_document_text",
    "get_document_structure",
    "find_document_by_code",
    "find_related_documents",
    "get_document_sections",
    "apply_document_change",
    "generate_change_notice",
    "generate_docx_report",
    "prepare_approval_route",
    "send_to_approval",
    "list_nd_control_departments",
    "list_nd_document_cards",
    "get_nd_document_card",
]
